obj-m += it6663.o 

ccflags-y += -I./

it6663-objs += i2csmbus.o 
it6663-objs += IT6664_hdmi2sp.o 
it6663-objs += IT6664_hdmi2_tx.o
it6663-objs += IT6664_hdmi2_rx.o 
it6663-objs += IT6664_IO.o 
it6663-objs += IT6664_EDID.o 
